unstable_features = true
fn_call_width = 80
array_width = 80
trailing_comma = "Never"
chain_indent = "Visual"
closure_block_indent_threshold = 1
comment_width = 80
combine_control_expr = true
condense_wildcard_suffices = true
fn_args_paren_newline = true
normalize_comments = true
use_try_shorthand = true
edition = "2021"
# blank_lines_lower_bound = 1
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = false
merge_imports = true
normalize_doc_attributes = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
use_small_heuristics = "Max"
imports_layout = "HorizontalVertical"
# Newlines are not wrapped correctly resulting in lines of varying length
wrap_comments = true
write_mode = "Overwrite"
reorder_imports = true
brace_style = "PreferSameLine"
fn_args_layout = "Tall"
fn_single_line = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
